options:
  cluster-name:
    type: string
    default: ""
    description: |
      Override the cluster name passed to the cinder CSI plugin.

      If unset, the charm uses the kube-control relation cluster tag.

  availability-zone:
    type: string
    default: ""
    description: |
      Availability zone to use with Cinder CSI. This is passed through to the
      parameters.availability field of the csi-cinder-default StorageClass.

  image-registry:
    type: string
    description: |
      Source registry of Cinder CSI storage images.

      By setting to a value, each image listed in the releases manifest
      has its image-registry replaced.

      If unset, the manifests will use the image registry from the kube-control relation

      example)
        juju config cinder-csi image-registry='rocks.canonical.com:443/cdk'
        juju config cinder-csi --reset image-registry

  web-proxy-enable:
    type: boolean
    description: |
      Whether the applications managed by this charm should be
      proxied using juju's model-config juju-*-proxy settings.
      (See https://documentation.ubuntu.com/juju/latest/reference/juju-cli/list-of-juju-cli-commands/model-config/).
    default: false

  reclaim-policy:
    type: string
    default: "Delete"
    description: |
      https://kubernetes.io/docs/concepts/storage/storage-classes/#reclaim-policy

      The reclaim policy for the PVCs created by the CSI driver. This is passed
      through to the parameters.reclaimPolicy field of the csi-cinder-default
      StorageClass.

      Potential values are "Delete" or "Retain"

  storage-class-default:
    type: boolean
    default: false
    description: |
      https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/

      Whether to set the storage class for the Cinder CSI driver as the cluster default
  storage-release:
    type: string
    description: |
      Specify the version of storage-release as defined by the `release`
      tags of https://github.com/kubernetes/cloud-provider-openstack

      example)
        juju config cinder-csi storage-release='v1.7.3'

      The manifests for the configured version must already be present in this
      charm source tree under upstream/cloud_storage/manifests.
      
      A list of supported versions is available through the action:
        juju run-action cinder-csi/leader list-releases --wait

      To reset by to the latest supported by the charm use:
        juju config cinder-csi --reset storage-release

      The current release deployed is available by viewing
        juju status cinder-csi

  topology:
    type: boolean
    default: True
    description: |
      Whether to enable the Cinder CSI topology awareness
